dist: focal
language: minimal

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
    gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev \
    libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

script:
  # تجهيز سورس TWRP
  - mkdir twrp && cd twrp
  - repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  - repo sync -j$(nproc) --force-sync

  # نسخ الـ device tree من الريبو بتاعك
  - cp -r ../device device

  # build TWRP
  - source build/envsetup.sh
  - lunch omni_X656-eng
  - mka recoveryimage
