dist: focal
language: minimal

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
    gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev libxml2-utils unzip

script:
  - mkdir twrp && cd twrp
  - repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  - repo sync -j$(nproc) --force-sync
  - cp -r ../device/infinix/X656 device/infinix/X656
  - source build/envsetup.sh
  - lunch omni_X656-eng
  - mka recoveryimage

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN     # هتحط token في إعدادات الريبو في Travis (Environment Variables)
  file: "twrp/out/target/product/X656/recovery.img"
  skip_cleanup: true
  on:
    tags: true
